### PR TITLE
Update all deps and move to netcore 2

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@7sharp9_exhumed ok this should work for Android again.
Things left for iOS:
* We need to apply manual iOS installation of https://github.com/react-community/react-native-image-picker/blob/develop/README.md#install
* We need a build target that calls ios build and packager instead of "run-android" 

I will continue to work on it Monday but maybe

**Comment by forki** [comment]
Btw I removed the onesignal component. I think it's way too complicated for a small sample

**Comment by forki** [comment]
But on the plus side: Hot Module Reloading should work

**Comment by forki** [comment]
https://facebook.github.io/react-native/docs/running-on-device.html for getting started on ios

**Comment by forki** [comment]
ok this is now working with HMR for android.

@7sharp9 @Krzysztof-Cieslak @alfonsogarciacaro I need someone with mac/ios to help with the 2 open points above for the iOS.

**Comment by alfonsogarciacaro** [comment]
I have a mac, I will try next week to have it working for iOS :+1:

**Comment by 7sharp9** [comment]
I'll take a look today.  I got the existing sample compiling yesterday just
not spawning the simulator.

**Pull request merged**
